MODBUS_READ         = 0x03
MODBUS_WRITE        = 0x10
MODBUS_DOUBLE_WR    = 0x20

"""
SENSORS BOARD DEFINES
"""
SENSORS_BOARD_READ_DISTANCE     = 1
SENSORS_BOARD_RELAY_STATE       = 2
SENSORS_BOARD_THRESHOLDS        = 3
SENSORS_BOARD_RELAY_MODE        = 4
SENSORS_BOARD_READ_DIGITAL_IN   = 5
SENSORS_BOARD_RAW_VALUES        = 6
SENSORS_BOARD_SET_MODE          = 7

# --------- RELAY STATE MODES------------
SENSORS_BOARD_RELAY_NONE        = 0
SENSORS_BOARD_RELAY_LOCK_HIGH   = 1
SENSORS_BOARD_RELAY_LOCK_LOW    = 2
# ------- SENSORS STATE MODES -----------
SENSORS_BOARD_MODE_NORMAL       = 0
SENSORS_BOARD_MODE_TANKING      = 1


"""
MAIN BOARD DEFINES
"""
MAIN_BOARD_OUTPUTS          = 0
MAIN_BOARD_READ_CURR_1_2    = 1
MAIN_BOARD_READ_CURR_3_4    = 2
MAIN_BOARD_READ_CURR_5_6    = 3
MAIN_BOARD_READ_CURR_7_8    = 4
MAIN_BOARD_READ_CURR_9_10   = 5
MAIN_BOARD_READ_DIGITAL_IN  = 6

"""
AMBIENT BOARD DEFINES
"""

AMBIENT_BOARD_READ_TEMP_PRESS = 1
AMBIENT_BOARD_READ_HUMID_GAS  = 2